[package]
name = "squiggles_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", rev="05a1b09" }
once_cell = "1.18.0"
num-traits = "0.2"
num-derive = "0.2"