name: Rust Test and Benchmark

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.0
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
      - name: rust-check
        run: cargo check --verbose
      - name: rust-test
        run: cargo test --verbose
            
            
