name: Rust Test and Benchmark

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4.11
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: check

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test

